/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdevapp;

import javax.swing.SwingUtilities;

/**
 *
 * @author djulzz
 */
public class StudentDialog extends javax.swing.JFrame {

    private MainWindow m_parent;
    /**
     * Creates new form StudentDialog
     */
    public StudentDialog( MainWindow parent ) {
        m_parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jLabel_First_Name = new javax.swing.JLabel();
        m_jTextField_First_Name = new javax.swing.JTextField();
        m_jLabel_Last_Name = new javax.swing.JLabel();
        m_jTextField_LastName = new javax.swing.JTextField();
        m_jLabel_DOB = new javax.swing.JLabel();
        m_jTextField_DOB = new javax.swing.JTextField();
        m_jButton_Add_Student = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        m_jLabel_First_Name.setText("First Name");

        m_jLabel_Last_Name.setText("Last Name");

        m_jTextField_LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jTextField_LastNameActionPerformed(evt);
            }
        });

        m_jLabel_DOB.setText("Date of Birth");

        m_jButton_Add_Student.setText("Add Student");
        m_jButton_Add_Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jButton_Add_StudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_jLabel_First_Name)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(m_jLabel_DOB)
                                .addComponent(m_jLabel_Last_Name)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_jTextField_First_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(m_jTextField_LastName)
                            .addComponent(m_jTextField_DOB)))
                    .addComponent(m_jButton_Add_Student))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_jLabel_First_Name)
                    .addComponent(m_jTextField_First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_jLabel_Last_Name)
                    .addComponent(m_jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_jLabel_DOB)
                    .addComponent(m_jTextField_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(m_jButton_Add_Student)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_jTextField_LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jTextField_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_jTextField_LastNameActionPerformed

    private void m_jButton_Add_StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jButton_Add_StudentActionPerformed
        // TODO add your handling code here:
        String FirstName = m_jTextField_First_Name.getText();
        String LastName = m_jTextField_LastName.getText();
        String DOB = m_jTextField_DOB.getText();
        MainWindow topFrame = ( MainWindow )this.getParent();
//        MainWindow topFrame = (MainWindow) SwingUtilities.getWindowAncestor(this);
//        if( null != topFrame )
//        {
//            topFrame.AddStudent(FirstName);
//        }

        m_parent.AddStudent(FirstName);

        //mw.toString();
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_m_jButton_Add_StudentActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentDialog().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_jButton_Add_Student;
    private javax.swing.JLabel m_jLabel_DOB;
    private javax.swing.JLabel m_jLabel_First_Name;
    private javax.swing.JLabel m_jLabel_Last_Name;
    private javax.swing.JTextField m_jTextField_DOB;
    private javax.swing.JTextField m_jTextField_First_Name;
    private javax.swing.JTextField m_jTextField_LastName;
    // End of variables declaration//GEN-END:variables
}
